stages:
  - build
  - deploy

build_release:
  stage: build
  variables:
    GIT_STRATEGY: clone
  only:
    - master
    - tags
  script: cargo build --release

deploy_release:
  stage: deploy
  needs: ["build_release"]
  only:
    - master
    - tags
    - /^[0-9]+\.[0-9]+\.[0-9]+\.0$/
  script:
    - call C:\novellLogin\login.bat
    - md "\\mach17\techdata\Release\ShellyRemoteHelper\%CI_COMMIT_TAG%"
    - xcopy_deploy ".\target\release\Shelly-Remote-Helper.exe" "\\mach17\techdata\Release\ShellyRemoteHelper\%CI_COMMIT_TAG%" /I /E /Y