stages:
  - build
  - deploy

build_release:
  stage: build
  variables:
    GIT_STRATEGY: clone
  only:
    - /^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/
    - master
  script: cargo build --release
  artifacts: 
    paths: 
      - target\release\*


deploy_release:
  stage: deploy
  needs: ["build_release"]
  only:
    - /^[0-9]+\.[0-9]+\.[0-9]+$/
  script:
    - call C:\novellLogin\login.bat
    - md "\\mach17\techdata\Release\ShellyRemoteHelper\%CI_COMMIT_TAG%"
    - xcopy_deploy ".\target\release\Shelly_Remote_Helper.exe" "\\mach17\techdata\Release\ShellyRemoteHelper\%CI_COMMIT_TAG%" /I /E /Y